# Generated by Django 3.1 on 2021-12-17 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.CharField(blank=True, max_length=600, verbose_name='Url'),
        ),
    ]
