# Generated by Django 3.1 on 2021-12-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produto_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='preco',
        ),
        migrations.AddField(
            model_name='produto',
            name='livro',
            field=models.FileField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
    ]
