# Generated by Django 3.1 on 2021-12-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211219_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='livro',
            field=models.FileField(upload_to='media/'),
        ),
    ]
