# Generated by Django 3.1 on 2021-12-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211219_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='link_real',
            field=models.CharField(blank=True, max_length=600, verbose_name='Loja'),
        ),
    ]
