# Generated by Django 3.1 on 2021-12-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_produto_link_real'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
