# Generated by Django 3.1 on 2021-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sinopse',
            field=models.CharField(default=1, max_length=1660, verbose_name='Sinopse'),
            preserve_default=False,
        ),
    ]
