# Generated by Django 3.1 on 2021-12-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_produto_sinopse'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=200, verbose_name='Subtitulo'),
        ),
    ]
