# Generated by Django 3.1 on 2022-01-13 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20211219_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='livro',
            field=models.FileField(upload_to='media/'),
        ),
    ]
