# Generated by Django 3.1 on 2022-01-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220113_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='livro',
            field=models.FileField(upload_to=''),
        ),
    ]
